spring:
  application:
    name: gateway-service
server:
  port: 8080

eureka:
  client:
    # colocamos true porque es un cliente
    fetch-registry: true                     # 🔄 Descarga el registro de Eureka
    register-with-eureka: true               # ✅ Se registra como cliente Eureka
    service-url:
      default-zone: http://localhost:8761/eureka  # 🌐 Dirección del Eureka Server

  instance:
    hostname: localhost
    #instance-id: hostname  # 🆔 Identificador único por instancia
    
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: usuario-service
          uri: lb://usuario-service
          predicates:
            - Path=/usuario/**
        - id: carro-service
          uri: lb://carro-service
          predicates:
            - Path=/carro/**
        - id: moto-service
          uri: lb://moto-service
          predicates:
            - Path=/moto/**
