spring:
  application:
    name: usuario-service
  datasource:
    url: jdbc:mysql://localhost:3306/microservice?useSSL=false&serverTimezone=UTC
    username: root
    password: mysql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: ${PORT:${SERVER_PORT:0}}

servicio:
  carro:
    url: http://localhost:8002

eureka:
  client:
    # colocamos true porque es un cliente
    fetch-registry: true                     # 🔄 Descarga el registro de Eureka
    register-with-eureka: true               # ✅ Se registra como cliente Eureka
    service-url:
      default-zone: http://localhost:8761/eureka  # 🌐 Dirección del Eureka Server

  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}  # 🆔 Identificador único por instancia

